/// 対空カットイン諸元

import { AntiAirCutinType } from "@/logics/antiAir/cutin/conditions"

type AaciData = {
    /** 変動ボーナス */
    mod: number,
    /** 最低保証ボーナス */
    guaranteed_bonus: number,
    /** 最低保証A */
    flat_A: number,
    /** 発動率 */
    rate: number,
    // TODO: オリジナルのpriority導出ロジックをdebugに実装する
    /** 優先度 小さいほど優先度が高い */
    priority: number,
}
type AaciDatas = Record<AntiAirCutinType, AaciData>

export const AACI_DATAS: AaciDatas = {
    1: {
        guaranteed_bonus: 7,
        rate: 0.65,
        mod: 1.7,
        flat_A: 3,
        priority: 12,
    },
    2: {
        guaranteed_bonus: 6,
        rate: 0.55,
        mod: 1.7,
        flat_A: 3,
        priority: 17,
    },
    3: {
        guaranteed_bonus: 4,
        rate: 0.5,
        mod: 1.6,
        flat_A: 2,
        priority: 31,
    },
    4: {
        guaranteed_bonus: 6,
        rate: 0.52,
        mod: 1.5,
        flat_A: 5,
        priority: 16,
    },
    5: {
        guaranteed_bonus: 4,
        rate: 0.5,
        mod: 1.5,
        flat_A: 2,
        priority: 32,
    },
    6: {
        guaranteed_bonus: 4,
        rate: 0.4,
        mod: 1.45,
        flat_A: 4,
        priority: 33,
    },
    7: {
        guaranteed_bonus: 3,
        rate: 0.45,
        mod: 1.35,
        flat_A: 2,
        priority: 41,
    },
    8: {
        guaranteed_bonus: 4,
        rate: 0.5,
        mod: 1.4,
        flat_A: 2,
        priority: 38,
    },
    9: {
        guaranteed_bonus: 2,
        rate: 0.4,
        mod: 1.3,
        flat_A: 1,
        priority: 51,
    },
    10: {
        guaranteed_bonus: 8,
        rate: 0.6,
        mod: 1.65,
        flat_A: 3,
        priority: 6,
    },
    11: {
        guaranteed_bonus: 6,
        rate: 0.55,
        mod: 1.5,
        flat_A: 2,
        priority: 9,
    },
    12: {
        guaranteed_bonus: 3,
        rate: 0.45,
        mod: 1.25,
        flat_A: 1,
        priority: 45,
    },
    13: {
        guaranteed_bonus: 4,
        rate: 0.35,
        mod: 1.35,
        flat_A: 1,
        priority: 39,
    },
    14: {
        guaranteed_bonus: 4,
        rate: 0.63,
        mod: 1.45,
        flat_A: 1,
        priority: 30,
    },
    15: {
        guaranteed_bonus: 3,
        rate: 0.55,
        mod: 1.3,
        flat_A: 1,
        priority: 40,
    },
    16: {
        guaranteed_bonus: 4,
        rate: 0.62,
        mod: 1.4,
        flat_A: 1,
        priority: 29,
    },
    17: {
        guaranteed_bonus: 2,
        rate: 0.55,
        mod: 1.25,
        flat_A: 1,
        priority: 48,
    },
    18: {
        guaranteed_bonus: 2,
        rate: 0.6,
        mod: 1.2,
        flat_A: 1,
        priority: 49,
    },
    19: {
        guaranteed_bonus: 5,
        rate: 0.55,
        mod: 1.45,
        flat_A: 1,
        priority: 26,
    },
    20: {
        guaranteed_bonus: 3,
        rate: 0.65,
        mod: 1.25,
        flat_A: 1,
        priority: 42,
    },
    21: {
        guaranteed_bonus: 5,
        rate: 0.6,
        mod: 1.45,
        flat_A: 1,
        priority: 27,
    },
    22: {
        guaranteed_bonus: 2,
        rate: 0.6,
        mod: 1.2,
        flat_A: 1,
        priority: 50,
    },
    23: {
        guaranteed_bonus: 1,
        rate: 0.8,
        mod: 1.05,
        flat_A: 1,
        priority: 52,
    },
    24: {
        guaranteed_bonus: 3,
        rate: 0.55,
        mod: 1.25,
        flat_A: 1,
        priority: 43,
    },
    25: {
        guaranteed_bonus: 7,
        rate: 0.6,
        mod: 1.55,
        flat_A: 1,
        priority: 10,
    },
    26: {
        guaranteed_bonus: 6,
        rate: 0.6,
        mod: 1.4,
        flat_A: 1,
        priority: 15,
    },
    27: {
        guaranteed_bonus: 5,
        rate: 0.55,
        mod: 1.55,
        flat_A: 1,
        priority: 20,
    },
    28: {
        guaranteed_bonus: 4,
        rate: 0.55,
        mod: 1.4,
        flat_A: 1,
        priority: 34,
    },
    29: {
        guaranteed_bonus: 5,
        rate: 0.6,
        mod: 1.55,
        flat_A: 1,
        priority: 28,
    },
    30: {
        guaranteed_bonus: 3,
        rate: 0.45,
        mod: 1.3,
        flat_A: 1,
        priority: 37,
    },
    31: {
        guaranteed_bonus: 2,
        rate: 0.5,
        mod: 1.25,
        flat_A: 1,
        priority: 46,
    },
    32: {
        guaranteed_bonus: 3,
        rate: 0.5,
        mod: 1.2,
        flat_A: 1,
        priority: 44,
    },
    33: {
        guaranteed_bonus: 3,
        rate: 0.42,
        mod: 1.35,
        flat_A: 1,
        priority: 36,
    },
    34: {
        guaranteed_bonus: 7,
        rate: 0.55,
        mod: 1.6,
        flat_A: 1,
        priority: 13,
    },
    35: {
        guaranteed_bonus: 6,
        rate: 0.54,
        mod: 1.55,
        flat_A: 1,
        priority: 18,
    },
    36: {
        guaranteed_bonus: 6,
        rate: 0.53,
        mod: 1.55,
        flat_A: 1,
        priority: 19,
    },
    37: {
        guaranteed_bonus: 4,
        rate: 0.44,
        mod: 1.45,
        flat_A: 1,
        priority: 35,
    },
    38: {
        guaranteed_bonus: 10,
        rate: 0.58,
        mod: 1.85,
        flat_A: 5,
        priority: 1,
    },
    39: {
        guaranteed_bonus: 10,
        rate: 0.57,
        mod: 1.7,
        flat_A: 5,
        priority: 2,
    },
    40: {
        guaranteed_bonus: 10,
        rate: 0.56,
        mod: 1.7,
        flat_A: 5,
        priority: 3,
    },
    41: {
        guaranteed_bonus: 9,
        rate: 0.55,
        mod: 1.65,
        flat_A: 5,
        priority: 5,
    },
    42: {
        guaranteed_bonus: 10,
        rate: 0.65,
        mod: 1.65,
        flat_A: 1,
        priority: 4,
    },
    43: {
        guaranteed_bonus: 8,
        rate: 0.58,
        mod: 1.6,
        flat_A: 1,
        priority: 7,
    },
    44: {
        guaranteed_bonus: 6,
        rate: 0.55,
        mod: 1.6,
        flat_A: 1,
        priority: 14,
    },
    45: {
        guaranteed_bonus: 5,
        rate: 0.5,
        mod: 1.55,
        flat_A: 1,
        priority: 21,
    },
    46: {
        guaranteed_bonus: 8,
        rate: 0.6,
        mod: 1.55,
        flat_A: 1,
        priority: 8,
    },
    47: {
        guaranteed_bonus: 2,
        rate: 0.7,
        mod: 1.3,
        flat_A: 1,
        priority: 47,
    },
    48: {
        guaranteed_bonus: 8,
        rate: 0.65,
        mod: 1.75,
        flat_A: 1,
        priority: 11,
    },
    49: {
        guaranteed_bonus: 5,
        rate: 0.5,
        mod: 1.5,
        flat_A: 1,
        priority: 23,
    },
    50: {
        guaranteed_bonus: 7,
        rate: 0.5,
        mod: 1.5,
        flat_A: 1,
        priority: 22,
    },
    51: {
        guaranteed_bonus: 5,
        rate: 0.5,
        mod: 1.35,
        flat_A: 1,
        priority: 24,
    },
    52: {
        guaranteed_bonus: 4,
        rate: 0.5,
        mod: 1.35,
        flat_A: 1,
        priority: 25
    }
}