import { FormationType } from "@/types";

export type CustomFormationType = Exclude<FormationType, 'Vanguard'>
    | 'VanguardFront'
    | 'VanguardRear'

type FormationData = {
    shellmod: number,
    torpmod: number,
    ASWmod: number,
    AAmod: number,
    shellacc: number,
    torpacc: number,
    NBacc: number,
    ASWacc: number,
    shellev: number,
    torpev: number,
    NBev: number,
    ASWev: number,
}

type FormationDatas = Record<CustomFormationType, FormationData>

const FORMATION_DATA: FormationDatas = {
    LineAhead: {
        shellmod: 1,
        torpmod: 1,
        ASWmod: .6,
        AAmod: 1,
        shellacc: 1,
        torpacc: 1,
        NBacc: 1,
        ASWacc: 1,
        shellev: 1,
        torpev: 1,
        NBev: 1,
        ASWev: 1,
    },
    DoubleLine: {
        shellmod: .8,
        torpmod: .8,
        ASWmod: .8,
        AAmod: 1.2,
        shellacc: 1.2,
        torpacc: .8,
        NBacc: .9,
        ASWacc: 1,
        shellev: 1,
        torpev: 1,
        NBev: 1,
        ASWev: 1,
    },
    Diamond: {
        shellmod: .7,
        torpmod: .7,
        ASWmod: 1.2,
        AAmod: 1.6,
        shellacc: 1,
        torpacc: .4,
        NBacc: .7,
        ASWacc: 1,
        shellev: 1.1,
        torpev: 1.1,
        NBev: 1,
        ASWev: 1,
    },
    Echelon: {
        shellmod: .75,
        torpmod: .6,
        ASWmod: 1.1,
        AAmod: 1,
        shellacc: 1.2,
        torpacc: .75,
        NBacc: .9,
        ASWacc: 1,
        shellev: 1.4,
        torpev: 1.3,
        NBev: 1.3,
        ASWev: 1.3,
    },
    LineAbreast: {
        shellmod: .6,
        torpmod: .6,
        ASWmod: 1.3,
        AAmod: 1,
        shellacc: 1.2,
        torpacc: .3,
        NBacc: .8,
        ASWacc: 1,
        shellev: 1.3,
        torpev: 1.4,
        NBev: 1.2,
        ASWev: 1.1,
    },
    VanguardFront: {
        shellmod: 0.5,
        torpmod: 1,
        ASWmod: 1,
        AAmod: 1.1,
        shellacc: .8,
        torpacc: .7,
        NBacc: .8,
        ASWacc: 1,
        shellev: 1,
        torpev: 1,
        NBev: 1,
        ASWev: 1,
    },
    VanguardRear: {
        shellmod: 1,
        torpmod: 1,
        ASWmod: .6,
        AAmod: 1.1,
        shellacc: 1.2,
        torpacc: .9,
        NBacc: 1.2,
        ASWacc: 1.1,
        shellev: 1,
        torpev: 1,
        NBev: 1,
        ASWev: 1,
    },
}