import { ShipType } from "../../types/ship/ship";

/**
 * ! 一段落するまで触らない
 */
const KETSUBAN_SHIP_DATAS = {
    9001: {
        name: 'Iona',
        nameJP: 'イオナ',
        type: ShipType.SS,
        HP: 70, HPmax: 78,
        FP: 129, FPbase: 100,
        TP: 129, TPbase: 110,
        AA: 59, AAbase: 40,
        AR: 99, ARbase: 60,
        EV: 69, EVbase: 50,
        ASW: 0, ASWbase: 0,
        LOS: 69, LOSbase: 60,
        LUK: 50, LUKmax: 59,
        RNG: 3,
        SLOTS: [0, 0],
        fuel: 150,
        ammo: 150
    },
    9002: {
        name: 'Takao (Fog)',
        nameJP: 'タカオ',
        type: ShipType.CA,
        can_laser: true,
        HP: 77, HPmax: 85,
        FP: 139, FPbase: 120,
        TP: 79, TPbase: 60,
        AA: 69, AAbase: 50,
        AR: 109, ARbase: 90,
        EV: 59, EVbase: 40,
        ASW: 0, ASWbase: 0,
        LOS: 79, LOSbase: 70,
        LUK: 20, LUKmax: 29,
        RNG: 3,
        SLOTS: [0, 0, 0],
        fuel: 175,
        ammo: 200
    },
    9003: {
        name: 'Haruna (Fog)',
        nameJP: 'ハルナ',
        type: ShipType.FBB,
        can_laser: true,
        HP: 102, HPmax: 111,
        FP: 149, FPbase: 135,
        TP: 0, TPbase: 0,
        AA: 79, AAbase: 60,
        AR: 119, ARbase: 110,
        EV: 49, EVbase: 37,
        ASW: 0, ASWbase: 0,
        LOS: 89, LOSbase: 80,
        LUK: 30, LUKmax: 39,
        RNG: 4,
        SLOTS: [0, 0, 0, 0],
        fuel: 200,
        ammo: 275
    },
    9011: {
        name: 'Nagara-Class mist',
        nameJP: 'ナガラ級mist',
        type: ShipType.CL,
        can_laser: true,
        HP: 55,
        FP: 75,
        TP: 60,
        AA: 30,
        AR: 66,
        EV: 28,
        ASW: 98,
        LOS: 80,
        LUK: 10,
        RNG: 3,
        SLOTS: [0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    9012: {
        name: 'Takao mist',
        nameJP: 'タカオmist',
        type: ShipType.CA,
        can_laser: true,
        HP: 77,
        FP: 150,
        TP: 60,
        AA: 50,
        AR: 100,
        EV: 40,
        ASW: 0,
        LOS: 70,
        LUK: 20,
        RNG: 3,
        SLOTS: [0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    9013: {
        name: 'Maya mist',
        nameJP: 'マヤmist',
        type: ShipType.CA,
        can_laser: true,
        HP: 79,
        FP: 160,
        TP: 60,
        AA: 50,
        AR: 105,
        EV: 39,
        ASW: 0,
        LOS: 70,
        LUK: 15,
        RNG: 3,
        SLOTS: [0, 0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    9014: {
        name: 'Haruna mist',
        nameJP: 'ハルナmist',
        type: ShipType.FBB,
        can_laser: true,
        HP: 102,
        FP: 200,
        TP: 0,
        AA: 60,
        AR: 130,
        EV: 37,
        ASW: 0,
        LOS: 80,
        LUK: 30,
        RNG: 4,
        SLOTS: [0, 0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    9015: {
        name: 'Kirishima mist',
        nameJP: 'キリシマmist',
        type: ShipType.FBB,
        can_laser: true,
        HP: 102,
        FP: 200,
        TP: 0,
        AA: 60,
        AR: 130,
        EV: 37,
        ASW: 0,
        LOS: 80,
        LUK: 20,
        RNG: 4,
        SLOTS: [0, 0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    9016: {
        name: 'Kongou mist',
        nameJP: 'コンゴウmist',
        type: ShipType.FBB,
        can_laser: true,
        HP: 142,
        FP: 280,
        TP: 0,
        AA: 70,
        AR: 150,
        EV: 50,
        ASW: 0,
        LOS: 90,
        LUK: 15,
        RNG: 4,
        SLOTS: [0, 0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    9017: {
        name: 'Nagara-Class *mist*',
        nameJP: 'ナガラ級*mist*',
        type: ShipType.CL,
        can_laser: true,
        HP: 55,
        FP: 60,
        TP: 60,
        AA: 25,
        AR: 46,
        EV: 18,
        ASW: 84,
        LOS: 50,
        LUK: 10,
        RNG: 3,
        SLOTS: [0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    9018: {
        name: 'Takao *mist*',
        nameJP: 'タカオ*mist*',
        type: ShipType.CA,
        can_laser: true,
        HP: 77,
        FP: 88,
        TP: 60,
        AA: 45,
        AR: 77,
        EV: 30,
        ASW: 0,
        LOS: 70,
        LUK: 20,
        RNG: 3,
        SLOTS: [0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    9019: {
        name: 'Maya *mist*',
        nameJP: 'マヤ*mist*',
        type: ShipType.CA,
        can_laser: true,
        HP: 79,
        FP: 98,
        TP: 60,
        AA: 45,
        AR: 87,
        EV: 29,
        ASW: 0,
        LOS: 70,
        LUK: 15,
        RNG: 3,
        SLOTS: [0, 0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    9020: {
        name: 'Haruna *mist*',
        nameJP: 'ハルナ*mist*',
        type: ShipType.FBB,
        can_laser: true,
        HP: 102,
        FP: 150,
        TP: 0,
        AA: 55,
        AR: 100,
        EV: 27,
        ASW: 0,
        LOS: 80,
        LUK: 30,
        RNG: 4,
        SLOTS: [0, 0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    9021: {
        name: 'Kirishima *mist*',
        nameJP: 'キリシマ*mist*',
        type: ShipType.FBB,
        can_laser: true,
        HP: 102,
        FP: 150,
        TP: 0,
        AA: 55,
        AR: 100,
        EV: 27,
        ASW: 0,
        LOS: 80,
        LUK: 20,
        RNG: 4,
        SLOTS: [0, 0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    9022: {
        name: 'Kongou *mist*',
        nameJP: 'コンゴウ*mist*',
        type: ShipType.FBB,
        can_laser: true,
        HP: 142,
        FP: 180,
        TP: 0,
        AA: 60,
        AR: 120,
        EV: 40,
        ASW: 0,
        LOS: 90,
        LUK: 15,
        RNG: 4,
        SLOTS: [0, 0, 0, 0],
        EQUIPS: [],
        fuel: 0,
        ammo: 0
    },
    3001: {
        name: '???????',
        nameJP: '???????',
        type: ShipType.CVB,
        HP: 92,
        FP: 89,
        TP: 0,
        AA: 99,
        AR: 102,
        EV: 59,
        ASW: 0,
        LOS: 89,
        LUK: 8,
        RNG: 3,
        SLOTS: [24, 18, 12, 6],
        fuel: 250,
        ammo: 220
    },
    3002: {
        name: '????? ?????????? ??????',
        nameJP: '????? ?????????? ??????',
        type: ShipType.BBV,
        can_laser: true,
        HP: 999,
        FP: 999,
        TP: 999,
        AA: 999,
        AR: 999,
        EV: 999,
        ASW: 999,
        LOS: 999,
        LUK: 99,
        RNG: 4,
        SLOTS: [999, 999, 999, 999],
        fuel: 10000,
        ammo: 10000,
        ACCbonus: 40
    },
}