import { DeepReadonly } from "@/types"
import { SpecialIcon } from "@/types/equip/player"
import { EquipImprovementType } from "../equip/improvement"

export const enum LandBasedPlaneType {
    LAND_BASED_BOMBER = 47,
    INTERCEPTOR = 48,
    LAND_BASED_SCOUT = 49,
    LAND_BASED_BOMBER_L = 53,
}

export type LandBasedPlaneData = {
    /** 装備名(EN) */
    name: string,
    /** 装備名(日) */
    nameJP: string,
    /** 装備種別ID */
    type: LandBasedPlaneType,
    /** 改修種別ID */
    improvement_type: EquipImprovementType,
    /** 装備種別とは別制御の装備アイコンID */
    icon?: SpecialIcon,
    /** 火力 */
    FP?: number,
    /** 雷装 */
    TP?: number,
    /** 対空 */
    AA?: number,
    /** 回避 */
    EV?: number,
    /** 装甲 */
    AR?: number,
    /** 対潜 */
    ASW?: number,
    /** 索敵 */
    LOS?: number,
    /** 爆装 */
    DIVEBOMB?: number,
    /** 対爆 */
    AB?: number,
    /** 迎撃 */
    IN?: number,
    /** 命中 */
    ACC?: number,
    /** 加重対空に対する対空射撃回避 */
    AA_resist_ship?: number,
    /** 艦隊防空に対する対空射撃回避 */
    AA_resist_fleet?: number,
    /** ロケット戦闘機であるか */
    is_rocket_fighter?: true,
    /** 反跳爆撃可能な爆撃機であるか */
    is_skip_bomber?: true,
}

export type EquipDatas = DeepReadonly<Record<number, LandBasedPlaneData>>

export const LAND_BASED_PLANE_DATAS: EquipDatas = {
    168: {
        name: 'Type 96 Land-based Attack Aircraft',
        nameJP: '九六式陸攻',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        DIVEBOMB: 10,
        TP: 8,
        AA: 1,
        ASW: 2,
        LOS: 2
    },
    169: {
        name: 'Type 1 Land-based Attack Aircraft',
        nameJP: '一式陸攻',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        DIVEBOMB: 12,
        TP: 10,
        AA: 2,
        ASW: 2,
        LOS: 3
    },
    170: {
        name: 'Type 1 Land-based Attack Aircraft (Nonaka Squadron)',
        nameJP: '一式陸攻(野中隊)',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        AA_resist_ship: .6,
        DIVEBOMB: 13,
        TP: 12,
        AA: 3,
        ASW: 2,
        ACC: 1,
        LOS: 4
    },
    175: {
        name: 'Raiden',
        nameJP: '雷電',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 6,
        AB: 5,
        IN: 2
    },
    176: {
        name: 'Type 3 Fighter Hien',
        nameJP: '三式戦 飛燕',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 8,
        AB: 1,
        IN: 3
    },
    177: {
        name: 'Type 3 Fighter Hien (244th Air Combat Group)',
        nameJP: '三式戦 飛燕(飛行第244戦隊)',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 9,
        AB: 3,
        IN: 4
    },
    180: {
        name: 'Type 1 Land-based Attack Aircraft Model 22A',
        nameJP: '一式陸攻 二二型甲',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        TP: 11,
        DIVEBOMB: 12,
        AA: 3,
        ASW: 2,
        LOS: 4,
    },

    185: {
        name: 'Type 3 Fighter Hien Model 1D',
        nameJP: '三式戦 飛燕一型丁',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 9,
        AB: 2,
        IN: 3,
    },
    186: {
        name: 'Type 1 Land-based Attack Aircraft Model 34',
        nameJP: '一式陸攻 三四型',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        DIVEBOMB: 12,
        TP: 11,
        AA: 4,
        ASW: 2,
        ACC: 1,
        LOS: 4,
    },
    187: {
        name: 'Ginga',
        nameJP: '銀河',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        DIVEBOMB: 14,
        TP: 14,
        AA: 3,
        ASW: 3,
        ACC: 1,
        LOS: 3,
    },
    201: {
        name: 'Shiden Model 11',
        nameJP: '紫電一一型',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 8,
        AR: 1,
        AB: 1,
        IN: 1,
    },
    202: {
        name: 'Shiden Model 21 Shiden Kai',
        nameJP: '紫電二一型 紫電改',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 9,
        AR: 2,
        AB: 1,
        IN: 3,
    },
    218: {
        name: 'Type 4 Fighter Hayate',
        nameJP: '四式戦 疾風',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 10,
        AB: 1,
        IN: 1,
    },
    221: {
        name: 'Type 1 Fighter Hayabusa Model II',
        nameJP: '一式戦 隼II型',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 6,
        IN: 2,
    },
    222: {
        name: 'Type 1 Fighter Hayabusa Model III A',
        nameJP: '一式戦 隼III型甲',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        FP: 1,
        AA: 7,
        AB: 1,
        IN: 3,
    },
    223: {
        name: 'Type 1 Fighter Hayabusa Model III A (54th Squadron)',
        nameJP: '一式戦 隼III型甲(54戦隊)',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        FP: 2,
        AA: 8,
        AB: 1,
        IN: 3,
        LOS: 1,
    },
    224: {
        name: 'Bomb-carrying Type 1 Fighter Hayabusa Model III Kai (65th Squadron)',
        nameJP: '爆装一式戦 隼III型改(65戦隊)',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        AA_resist_ship: .6,
        AA_resist_fleet: .7,
        FP: 3,
        DIVEBOMB: 9,
        AA: 6,
        ACC: 4,
        EV: 2,
        LOS: 1,
    },
    225: {
        name: 'Type 1 Fighter Hayabusa Model II (64th Squadron)',
        nameJP: '一式戦 隼II型(64戦隊)',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        FP: 1,
        AA: 11,
        AB: 1,
        IN: 5,
        LOS: 1,
    },
    250: {
        name: 'Spitfire Mk.I',
        nameJP: 'Spitfire Mk.I',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        FP: 1,
        AA: 7,
        AB: 2,
        IN: 1,
    },
    251: {
        name: 'Spitfire Mk.V',
        nameJP: 'Spitfire Mk.V',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        FP: 1,
        AA: 9,
        AB: 3,
        IN: 2,
    },
    253: {
        name: 'Spitfire Mk.IX (Skilled)',
        nameJP: 'Spitfire Mk.IX(熟練)',
        icon: SpecialIcon.ArmyLandBasedFighters,
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        FP: 1,
        AA: 10,
        AB: 2,
        IN: 4,
    },
    263: {
        name: 'Shiden Kai (343rd Air Group) 301st Fighter Squadron',
        nameJP: '紫電改(三四三空) 戦闘301',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 11,
        AR: 2,
        AB: 2,
        IN: 4,
    },
    264: {
        name: 'Shiden Kai (343 Air Group) 701st Fighter Squadron',
        nameJP: '紫電改(三四三空) 戦闘701',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 11,
        AR: 2,
        AB: 2,
        IN: 4,
    },
    265: {
        name: 'Shiden Kai (343 Air Group) 407th Fighter Squadron',
        nameJP: '紫電改(三四三空) 戦闘407',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 11,
        AR: 2,
        AB: 2,
        IN: 4,
    },
    269: {
        name: 'Prototype Toukai',
        nameJP: '試製東海',
        icon: SpecialIcon.LandBasedPatrolAircraft,
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        DIVEBOMB: 2,
        ASW: 10,
        LOS: 5,
    },
    270: {
        name: 'Toukai (901 Air Group)',
        nameJP: '東海(九〇一空)',
        icon: SpecialIcon.LandBasedPatrolAircraft,
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        DIVEBOMB: 2,
        ACC: 1,
        ASW: 11,
        LOS: 6,
    },
    311: {
        name: 'Type 2 Land-based Reconnaissance Aircraft',
        nameJP: '二式陸上偵察機',
        type: LandBasedPlaneType.LAND_BASED_SCOUT,
        improvement_type: EquipImprovementType.LAND_BASED_SCOUT,
        AA: 3,
        ACC: 2,
        LOS: 8,
    },
    312: {
        name: 'Type 2 Land-based Reconnaissance Aircraft (Skilled)',
        nameJP: '二式陸上偵察機(熟練)',
        type: LandBasedPlaneType.LAND_BASED_SCOUT,
        improvement_type: EquipImprovementType.LAND_BASED_SCOUT,
        AA: 3,
        AR: 1,
        ACC: 3,
        LOS: 9,
    },
    333: {
        name: 'Reppuu Kai',
        nameJP: '烈風改',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 10,
        AR: 1,
        AB: 6,
        IN: 2,
    },
    334: {
        name: 'Reppuu Kai (352 Air Group/Skilled)',
        nameJP: '烈風改(三五二空/熟練)',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 11,
        AR: 1,
        AB: 7,
        IN: 3,
    },
    350: {
        name: 'Me163B',
        nameJP: 'Me163B',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        is_rocket_fighter: true,
        AA: 2,
        AB: 9,
    },
    351: {
        name: 'Prototype Shuusui',
        nameJP: '試製 秋水',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        is_rocket_fighter: true,
        AA: 2,
        AB: 8,
    },
    352: {
        name: 'Shuusui',
        nameJP: '秋水',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        is_rocket_fighter: true,
        AA: 3,
        AB: 9,
    },
    354: {
        name: 'Fw190 D-9',
        nameJP: 'Fw190 D-9',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        FP: 2,
        AA: 12,
        AB: 3,
        IN: 3,
    },
    388: {
        name: 'Ginga (Egusa Squadron)',
        nameJP: '銀河(江草隊)',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        AA_resist_ship: .6,
        DIVEBOMB: 15,
        TP: 15,
        AA: 3,
        ACC: 3,
        ASW: 4,
        LOS: 4,
    },
    395: {
        name: 'Shinzan',
        nameJP: '深山',
        type: LandBasedPlaneType.LAND_BASED_BOMBER_L,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER_L,
        DIVEBOMB: 17,
        TP: 16,
        AA: 1,
    },
    396: {
        name: 'Shinzan Kai',
        nameJP: '深山改',
        type: LandBasedPlaneType.LAND_BASED_BOMBER_L,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER_L,
        DIVEBOMB: 19,
        TP: 17,
        AA: 2,
    },
    401: {
        name: 'Do 17 Z-2',
        nameJP: 'Do 17 Z-2',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        DIVEBOMB: 11,
        AA: 2,
        ASW: 5,
        LOS: 2,
    },
    403: {
        name: 'Type 4 Heavy Bomber Hiryuu',
        nameJP: '四式重爆 飛龍',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        DIVEBOMB: 15,
        TP: 14,
        AA: 5,
        ACC: 1,
        ASW: 4,
        LOS: 4,
    },
    404: {
        name: 'Type 4 Heavy Bomber Hiryuu (Skilled)',
        nameJP: '四式重爆 飛龍(熟練)',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        AA_resist_ship: .6,
        DIVEBOMB: 16,
        TP: 14,
        AA: 5,
        ACC: 2,
        ASW: 5,
        LOS: 5,
    },
    405: {
        name: 'Do 217 E-5 + Hs293 Initial Model',
        nameJP: 'Do 217 E-5+Hs293初期型',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        AA_resist_ship: .6,
        DIVEBOMB: 22,
        TP: 13,
        AA: 4,
        ACC: 2,
        LOS: 3,
    },
    406: {
        name: 'Do 217 K-2 + Fritz-X',
        nameJP: 'Do 217 K-2+Fritz-X',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        AA_resist_ship: .6,
        DIVEBOMB: 24,
        TP: 16,
        AA: 4,
        ACC: 2,
        LOS: 3,
    },
    416: {
        name: 'Type 0 Fighter Model 21 (Tainan Air Group)',
        nameJP: '零式艦戦21型(台南空)',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 11,
        AB: 1,
        IN: 3,
        LOS: 1,
    },
    417: {
        name: 'Type 0 Fighter Model 32 (Tainan Air Group)',
        nameJP: '零式艦戦32型(台南空)',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 12,
        AB: 1,
        IN: 4,
        LOS: 1,
    },
    418: {
        name: 'Type 0 Fighter Model 22 (251 Air Group)',
        nameJP: '零式艦戦22型(251空)',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        AA: 12,
        AB: 1,
        IN: 3,
        LOS: 1,
    },
    431: {
        name: 'SM.79',
        nameJP: 'SM.79',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        DIVEBOMB: 13,
        TP: 9,
        AA: 2,
        ASW: 3,
        LOS: 2,
    },
    432: {
        name: 'SM.79 bis',
        nameJP: 'SM.79 bis',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        DIVEBOMB: 14,
        TP: 12,
        AA: 3,
        ASW: 4,
        LOS: 3,
    },
    433: {
        name: 'SM.79 bis (Skilled)',
        nameJP: 'SM.79 bis(熟練)',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        AA_resist_ship: .6,
        DIVEBOMB: 14,
        TP: 13,
        AA: 3,
        ACC: 2,
        ASW: 4,
        LOS: 3,
    },
    444: {
        name: 'Type 4 Heavy Bomber Hiryuu + No.1 Model 1A Guided Missile',
        nameJP: '四式重爆 飛龍+イ号一型甲 誘導弾',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        AA_resist_ship: .6,
        DIVEBOMB: 20,
        TP: 15,
        AA: 5,
        ACC: 1,
        ASW: 3,
        LOS: 4,
    },
    445: {
        name: 'Type 2 Two-seat Fighter Toryuu',
        nameJP: '二式複戦 屠龍',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        icon: SpecialIcon.ArmyLandBasedFighters,
        AA: 3,
        AR: 1,
        AB: 4,
        IN: 1,
    },
    446: {
        name: 'Type 2 Two-seat Fighter Toryuu Model C',
        nameJP: '二式複戦 屠龍 丙型',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        icon: SpecialIcon.ArmyLandBasedFighters,
        AA: 3,
        AR: 2,
        AB: 6,
        IN: 2,
    },
    452: {
        name: 'Ki-96',
        nameJP: 'キ96',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        icon: SpecialIcon.ArmyLandBasedFighters,
        AA: 5,
        AR: 2,
        AB: 5,
        IN: 4,
    },
    453: {
        name: 'Ki-102 B',
        nameJP: 'キ102乙',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        icon: SpecialIcon.LandBasedRaidAircraft,
        AA_resist_ship: .6,
        FP: 4,
        DIVEBOMB: 19,
        TP: 11,
        AA: 4,
        ACC: 4,
        ASW: 4,
    },
    454: {
        name: 'Ki-102 B Kai + No.1 Model 1B Guided Missile',
        nameJP: 'キ102乙改+イ号一型乙 誘導弾',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        icon: SpecialIcon.LandBasedRaidAircraft,
        AA_resist_ship: .6,
        AA_resist_fleet: .7,
        FP: 4,
        DIVEBOMB: 20,
        TP: 14,
        AA: 3,
        ACC: 3,
        ASW: 4,
    },
    459: {
        name: 'B-25',
        nameJP: 'B-25',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        is_skip_bomber: true,
        FP: 3,
        DIVEBOMB: 16,
        TP: 8,
        AA: 4,
        LOS: 4,
    },
    479: {
        name: 'Mosquito FB Mk.VI',
        nameJP: 'Mosquito FB Mk.VI',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        AA_resist_ship: .6,
        AA_resist_fleet: .7,
        DIVEBOMB: 18,
        TP: 5,
        AA: 5,
        ACC: 1,
        ASW: 4,
        LOS: 5,
    },
    480: {
        name: 'Mosquito PR Mk.IV',
        nameJP: 'Mosquito PR Mk.IV',
        type: LandBasedPlaneType.LAND_BASED_SCOUT,
        improvement_type: EquipImprovementType.LAND_BASED_SCOUT,
        AR: 2,
        ACC: 2,
        LOS: 9,
    },
    484: {
        name: 'Type 4 Heavy Bomber Hiryuu (Skilled) + No.1 Model 1A Guided Missile',
        nameJP: '四式重爆 飛龍(熟練)+イ号一型甲 誘導弾',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        AA_resist_ship: .6,
        DIVEBOMB: 21,
        TP: 17,
        AA: 5,
        ACC: 3,
        ASW: 4,
        LOS: 5,
    },
    493: {
        name: 'Type 1 Land-based Attack Aircraft (Hachiman Force)',
        nameJP: '一式陸攻(八幡部隊)',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        DIVEBOMB: 12,
        TP: 11,
        AA: 3,
        ACC: 1,
        ASW: 2,
        LOS: 4,
    },
    504: {
        name: 'Ginga (Skilled)',
        nameJP: '銀河(熟練)',
        type: LandBasedPlaneType.LAND_BASED_BOMBER,
        improvement_type: EquipImprovementType.LAND_BASED_BOMBER,
        AA_resist_ship: .6,
        DIVEBOMB: 15,
        TP: 14,
        AA: 3,
        ACC: 2,
        ASW: 3,
        LOS: 3,
    },
    516: {
        name: 'Me 262 A-1a/R1',
        nameJP: 'Me 262 A-1a/R1',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        icon: SpecialIcon.JetLandBasedFighters,
        DIVEBOMB: 3,
        AA: 15,
        AB: 6,
        IN: 1,
    },
    546: {
        name: 'Prototype Shinden (LB Interceptor)',
        nameJP: '試製 震電(局地戦闘機)',
        type: LandBasedPlaneType.INTERCEPTOR,
        improvement_type: EquipImprovementType.INTERCEPTOR,
        icon: SpecialIcon.PropulsionLandBasedFighters,
        AA: 14,
        AB: 5,
        IN: 4,
    },
}