import { SpecialIcon } from "@/types/equip/player";
import { AbyssalEquipDatas } from "@/types/equip/abbysal";

export const ABYSSAL_EQUIP_DATAS: AbyssalEquipDatas = {
    1501: {
        name: '5inch Single Cannon',
        nameJP: '5inch単装砲',
        type: "MAIN_GUN_S",
        aaci_type: 'A_GUN',
        FP: 1,
        RNG: 1,
    },
    1502: {
        name: '5inch Twin Cannon',
        nameJP: '5inch連装砲',
        type: "MAIN_GUN_S",
        aaci_type: 'A_GUN',
        FP: 2,
        RNG: 1,
    },
    1503: {
        name: '3inch Single High-Angle Mount',
        nameJP: '3inch単装高角砲',
        type: "MAIN_GUN_S",
        icon: SpecialIcon.MainHighAngleGun,
        aaci_type: 'A_HAGUN', //regular gun in AA calculation?
        FP: 1,
        AA: 1,
        RNG: 1,
    },
    1504: {
        name: '5inch Single AA Cannon',
        nameJP: '5inch単装高射砲',
        type: "MAIN_GUN_M",
        aaci_type: 'A_GUN',
        FP: 2,
        AA: 2,
        RNG: 2,
    },
    1505: {
        name: '8inch Triple Cannon',
        nameJP: '8inch三連装砲',
        type: "MAIN_GUN_M",
        aaci_type: 'A_GUN',
        FP: 8,
        AA: 2,
        RNG: 2,
    },
    1506: {
        name: '6inch Twin Rapid-fire Cannon',
        nameJP: '6inch連装速射砲',
        type: "MAIN_GUN_M",
        aaci_type: 'A_GUN',
        FP: 3,
        AA: 3,
        RNG: 2,
    },
    1507: {
        name: '14inch Twin Cannon',
        nameJP: '14inch連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 10,
        AA: 4,
        RNG: 3,
    },
    1508: {
        name: '16inch Twin Cannon',
        nameJP: '16inch連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 15,
        AA: 4,
        RNG: 3,
    },
    1509: {
        name: '16inch Triple Cannon',
        nameJP: '16inch三連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 20,
        AA: 5,
        RNG: 3,
    },
    1510: {
        name: '5inch High-Angle Mount (Secondary)',
        nameJP: '5inch単装高射砲',
        type: "SECONDARY_GUN",
        aaci_type: 'A_HAGUN',
        icon: SpecialIcon.MainHighAngleGun,
        FP: 1,
        AA: 2,
        RNG: 1,
    },
    1511: {
        name: '6inch Single Cannon',
        nameJP: '6inch単装砲',
        type: "SECONDARY_GUN",
        aaci_type: 'A_GUN',
        FP: 1,
        RNG: 2,
    },
    1512: {
        name: '12.5inch Twin Secondary Cannon',
        nameJP: '12.5inch連装副砲',
        type: "SECONDARY_GUN",
        aaci_type: 'A_GUN',
        FP: 7,
        AA: 3,
        RNG: 2,
    },
    1513: {
        name: '21inch Torpedo Mk.I',
        nameJP: '21inch魚雷前期型',
        type: "TORPEDO",
        aaci_type: 'NONE',
        TP: 2,
        RNG: 1,
    },
    1514: {
        name: '21inch Torpedo Mk.II',
        nameJP: '21inch魚雷後期型',
        type: "TORPEDO",
        aaci_type: 'NONE',
        TP: 5,
        RNG: 1,
    },
    1515: {
        name: 'High-speed Abyssal Torpedo',
        nameJP: '高速深海魚雷',
        type: "TORPEDO",
        aaci_type: 'NONE',
        TP: 10,
        RNG: 1,
    },
    1516: {
        name: 'Abyssal Torpedo Bomber Mk.I',
        nameJP: '深海棲艦攻',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        AERIAL_TP: 4,
        ASW: 2,
        LOS: 5,
    },
    1517: {
        name: 'Abyssal Torpedo Bomber Mk.II',
        nameJP: '深海棲艦攻 Mark.II',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        AERIAL_TP: 6,
        ASW: 4,
        LOS: 5,
    },
    1518: {
        name: 'Abyssal Torpedo Bomber Mk.III',
        nameJP: '深海棲艦攻 Mark.III',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        AERIAL_TP: 11,
        AA: 4,
        ASW: 7,
        LOS: 5,
    },
    1519: {
        name: 'Abyssal Fighter',
        nameJP: '深海棲艦戦',
        type: "FIGHTER",
        aaci_type: 'NONE',
        AA: 2,
    },
    1520: {
        name: 'Abyssal Fighter Mk.II',
        nameJP: '深海棲艦戦 Mark.II',
        type: "FIGHTER",
        aaci_type: 'NONE',
        AA: 5,
    },
    1521: {
        name: 'Abyssal Fighter Mk.III',
        nameJP: '深海棲艦戦 Mark.III',
        type: "FIGHTER",
        aaci_type: 'NONE',
        AA: 9,
    },
    1522: {
        name: 'Flying-fish Fighter',
        nameJP: '飛び魚艦戦',
        type: "FIGHTER",
        aaci_type: 'NONE',
        AA: 13,
    },
    1523: {
        name: 'Abyssal Dive Bomber Mk.I',
        nameJP: '深海棲艦爆',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        AERIAL_BOMB: 3,
        ASW: 1,
    },
    1524: {
        name: 'Abyssal Dive Bomber Mk.II',
        nameJP: '深海棲艦爆 Mark.II',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        AERIAL_BOMB: 6,
        ASW: 2,
    },
    1525: {
        name: 'Abyssal Recon Plane',
        nameJP: '深海棲艦偵察機',
        type: "SEAPLANE",
        aaci_type: 'NONE',
        AERIAL_BOMB: 1,
        AA: 1,
        ASW: 1,
        LOS: 5,
    },
    1526: {
        name: 'Flying-fish Recon Plane',
        nameJP: '飛び魚偵察機',
        type: "SEAPLANE",
        aaci_type: 'NONE',
        AERIAL_BOMB: 4,
        AA: 2,
        ASW: 2,
        LOS: 10,
    },
    1527: {
        name: 'Air Radar Mark.I',
        nameJP: '対空レーダ― Mark.I',
        type: "RADAR_S",
        aaci_type: 'A_AIRRADAR',
        AA: 5,
        LOS: 5,
        ACC: 5,
    },
    1528: {
        name: 'Surface Radar Mark.I',
        nameJP: '水上レーダ― Mark.I',
        type: "RADAR_S",
        aaci_type: 'NONE',
        LOS: 5,
        ACC: 10,
    },
    1529: {
        name: 'Surface Radar Mark.II',
        nameJP: '水上レーダ― Mark.II',
        type: "RADAR_S",
        aaci_type: 'NONE',
        LOS: 10,
        ACC: 15,
    },
    1530: {
        name: 'Air Radar Mark.II',
        nameJP: '対空レーダ― Mark.II',
        type: "RADAR_L",
        aaci_type: 'A_AIRRADAR',
        AA: 10,
        LOS: 10,
        ACC: 5,
    },
    1531: {
        name: 'Abyssal Surface Radar',
        nameJP: '深海水上レーダー',
        type: "RADAR_L",
        aaci_type: 'A_AIRRADAR',
        AA: 5,
        EV: 3,
        ASW: 5,
        LOS: 16,
        ACC: 24,
    },
    1532: {
        name: 'Abyssal Air Radar',
        nameJP: '深海対空レーダ―',
        type: "RADAR_L",
        aaci_type: 'A_AIRRADAR',
        AA: 18,
        EV: 2,
        ASW: 5,
        LOS: 12,
        ACC: 16,
    },
    1533: {
        name: 'Improved Abyssal Turbine',
        nameJP: '改良型深海タービン',
        type: "ENGINE",
        aaci_type: 'NONE',
        EV: 10,
    },
    1534: {
        name: 'Enhanced Abyssal Engine',
        nameJP: '強化型深海缶',
        type: "ENGINE",
        aaci_type: 'NONE',
        EV: 15,
    },
    1535: {
        name: 'Abyssal AA Dispersal Shell',
        nameJP: '対空散弾',
        type: "TYPE_3_SHELL",
        aaci_type: 'A_TYPE3SHELL',
        AA: 10,
    },
    1536: {
        name: 'Depleted AP Shell',
        nameJP: '劣化徹甲弾',
        type: "AP_SHELL",
        aaci_type: 'NONE',
        FP: 15,
        ACC: 5,
    },
    1537: {
        name: '12.7mm Abyssal Gun',
        nameJP: '12.7mm機銃',
        type: "AA_GUN",
        aaci_type: 'A_AAGUN',
        AA: 2,
    },
    1538: {
        name: '20mm Abyssal Gun',
        nameJP: '20mm機銃',
        type: "AA_GUN",
        aaci_type: 'A_AAGUN',
        AA: 4,
    },
    1539: {
        name: '40mm Abyssal Twin Autocannon',
        nameJP: '40mm二連装機関砲',
        type: "AA_GUN",
        aaci_type: 'A_AAGUN',
        AA: 8,
    },
    1540: {
        name: '40mm Abyssal Quad Autocannon',
        nameJP: '40mm四連装機関砲',
        type: "AA_GUN",
        aaci_type: 'A_AAGUN',
        is_concentrated: true,
        AA: 12,
    },
    1541: {
        name: 'Abyssal Cuttlefish Torpedo',
        nameJP: '深海烏賊魚雷',
        type: "MIDGET_SUBMARINE",
        aaci_type: 'NONE',
        TP: 18,
        ACC: 5,
        RNG: 1,
    },
    1542: {
        name: 'Abyssal Depth Charge Projector',
        nameJP: '深海爆雷投射機',
        type: "DEPTH_CHARGE",
        aaci_type: 'NONE',
        ASW: 7,
    },
    1543: {
        name: 'Abyssal Sonar',
        nameJP: '深海ソナー',
        type: "SONAR_S",
        aaci_type: 'NONE',
        ASW: 9,
    },
    1544: {
        name: 'Abyssal Depth Charge Projector Mk.II',
        nameJP: '深海爆雷投射機 Mk.II',
        type: "DEPTH_CHARGE",
        aaci_type: 'NONE',
        ASW: 13,
    },
    1545: {
        name: 'Abyssal Sonar Mk.II',
        nameJP: '深海ソナー Mk.II',
        type: "SONAR_S",
        aaci_type: 'NONE',
        ASW: 16,
    },
    1546: {
        name: 'Flying-fish Dive Bomber',
        nameJP: '飛び魚艦爆',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        AERIAL_BOMB: 10,
        AA: 8,
        ASW: 7,
    },
    1547: {
        name: 'Abyssal Cat Fighter',
        nameJP: '深海猫艦戦',
        type: "FIGHTER",
        aaci_type: 'NONE',
        AA: 10,
        ACC: 1,
    },
    1548: {
        name: 'Abyssal Hell Diver',
        nameJP: '深海地獄艦爆',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        AERIAL_BOMB: 11,
        ASW: 4,
        LOS: 3,
        ACC: 3,
    },
    1549: {
        name: 'Avenger Torpedo Bomber',
        nameJP: '深海復讐艦攻',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        AERIAL_TP: 13,
        AA: 4,
        ASW: 5,
        LOS: 5,
        ACC: 2,
    },
    1550: {
        name: '5inch Twin Dual-Purpose Cannon',
        nameJP: '5inch連装両用莢砲',
        type: "MAIN_GUN_S",
        aaci_type: 'A_HAFD',
        icon: SpecialIcon.MainHighAngleGun,
        FP: 2,
        AA: 9,
        RNG: 2,
        ACC: 3,
    },
    1551: {
        name: '20inch Twin Cannon',
        nameJP: '20inch連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 27,
        AA: 4,
        RNG: 3,
        ACC: 3,
    },
    1552: {
        name: '15inch Fortress Gun',
        nameJP: '15inch要塞砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 13,
        AR: 3,
        RNG: 3,
        ACC: 4,
    },
    1553: {
        name: '4inch Dual-Purpose+CIC',
        nameJP: '4inch連装両用砲+CIC',
        type: "MAIN_GUN_S",
        aaci_type: 'A_HAFD',
        icon: SpecialIcon.MainHighAngleGun,
        FP: 5,
        AA: 15,
        RNG: 2,
        ACC: 5,
    },
    1554: {
        name: 'Abyssal Attack Seaplane',
        nameJP: '深海水上攻撃機',
        type: "SEAPLANE_BOMBER",
        aaci_type: 'NONE',
        AERIAL_BOMB: 8,
        AA: 4,
        ASW: 8,
        LOS: 6,
        ACC: 1,
    },
    1555: {
        name: 'Abyssal Attack Seaplane Kai',
        nameJP: '深海水上攻撃機改',
        type: "SEAPLANE_BOMBER",
        aaci_type: 'NONE',
        AERIAL_BOMB: 13,
        AA: 9,
        ASW: 10,
        LOS: 7,
        ACC: 3,
    },
    1556: {
        name: 'Abyssal Cat Fighter Kai',
        nameJP: '深海猫艦戦改',
        type: "FIGHTER",
        aaci_type: 'NONE',
        AA: 12,
        EV: 2,
        ACC: 2,
    },
    1557: {
        name: 'Abyssal Hell Diver Kai',
        nameJP: '深海地獄艦爆改',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        AERIAL_BOMB: 15,
        ASW: 8,
        LOS: 5,
        ACC: 4,
    },
    1558: {
        name: 'Avenger Torpedo Bomber Kai',
        nameJP: '深海復讐艦攻改',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        AERIAL_TP: 16,
        AA: 5,
        ASW: 9,
        LOS: 6,
        ACC: 3,
    },
    1559: {
        name: 'Abyssal FCS + CIC',
        nameJP: '深海FCS+CIC',
        type: "SONAR_S",
        aaci_type: 'A_GUN', //.2 mult
        AA: 6,
        ASW: 20,
        EV: 3,
        LOS: 3,
        ACC: 5
    },
    1560: {
        name: 'Abyssal Searchlight',
        nameJP: '深海探照灯',
        type: "SEARCHLIGHT_S",
        aaci_type: 'NONE',
        FP: 2,
        LOS: 2
    },
    1561: {
        name: 'Abyssal Liberation Land-based Dive Bomber',
        nameJP: '深海解放陸爆',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        AERIAL_BOMB: 11,
        AA: 3,
        ASW: 5,
        ACC: 1,
        LOS: 3
    },
    1562: {
        name: 'Abyssal Liberation Land-based Dive Bomber Ace',
        nameJP: '深海解放陸爆Ace',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        AERIAL_BOMB: 16,
        AA: 5,
        ASW: 7,
        ACC: 2,
        LOS: 4
    },
    1563: {
        name: '8inch Long Range Twin Gun Mount',
        nameJP: '8inch長射程連装砲',
        type: "MAIN_GUN_M",
        aaci_type: 'A_GUN',
        FP: 8,
        AA: 1,
        ACC: -1,
        RNG: 3
    },
    1564: {
        name: 'Abyssal Reconnaissance Observation Seaplane',
        nameJP: '深海水上偵察観測機',
        type: "SEAPLANE",
        aaci_type: 'NONE',
        AA: 2,
        ASW: 2,
        ACC: 5,
        LOS: 5
    },
    1565: {
        name: '5inch Coastal Gun',
        nameJP: '5inch沿岸設置砲',
        type: "MAIN_GUN_S",
        aaci_type: 'A_GUN',
        FP: 3,
        AR: 2,
        ACC: 3,
        RNG: 2
    },
    1566: {
        name: 'Abyssal Cat Fighter (Bombing)',
        nameJP: '深海猫艦戦(爆装)',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        AERIAL_BOMB: 8,
        AA: 7,
        ASW: 2,
        ACC: 2
    },
    1567: {
        name: 'Coastal Radar',
        nameJP: '沿岸設置レーダー',
        type: "RADAR_L",
        aaci_type: 'A_AIRRADAR',
        AA: 4,
        ACC: 16,
        LOS: 8
    },
    1568: {
        name: '16inch Triple Gun Mount (Abyssal)',
        nameJP: '16inch三連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 24,
        AA: 3,
        AR: 1,
        ACC: 4,
        RNG: 3
    },
    1569: {
        name: 'Abyssal Reconnaissance Flying Boat',
        nameJP: '深海偵察飛行艇',
        type: "SEAPLANE",
        aaci_type: 'NONE',
        FP: 3,
        AA: 1,
        ASW: 2,
        ACC: 8,
        LOS: 9
    },
    1570: {
        name: 'High-speed Abyssal Torpedo mod. 2',
        nameJP: '高速深海魚雷 mod.2',
        type: "MIDGET_SUBMARINE",
        aaci_type: 'NONE',
        can_not_op_torpedo_midgetsub: true,
        TP: 13,
        ACC: 3,
        RNG: 1,
    },
    1571: {
        name: 'Abyssal Seaplane Tender Imp Aircraft',
        nameJP: '深海水母小鬼機',
        type: "SEAPLANE_BOMBER",
        aaci_type: 'NONE',
        FP: 4,
        AERIAL_BOMB: 15,
        AA: 11,
        AR: 4,
        ASW: 15,
        ACC: 8,
        LOS: 8,
        RNG: 4,
    },
    1572: {
        name: 'Abyssal Bearcat Fighter',
        nameJP: '深海熊猫艦戦',
        type: "FIGHTER",
        aaci_type: 'NONE',
        FP: 8,
        AA: 18,
        AR: 8,
        ACC: 8,
        EV: 8,
    },
    1573: {
        name: 'Abyssal Submarine Floatplane',
        nameJP: '深海潜水下駄履き',
        type: "SEAPLANE_BOMBER",
        aaci_type: 'NONE',
        FP: 6,
        AERIAL_BOMB: 18,
        AA: 6,
        AR: 3,
        ASW: 9,
        ACC: 12,
        EV: 6,
        LOS: 3,
        RNG: 5,
    },
    1574: {
        name: 'Abyssal Patrolling Attack Hawk',
        nameJP: '深海攻撃哨戒鷹',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        FP: 3,
        AERIAL_BOMB: 14,
        AA: 8,
        AR: 3,
        ACC: 8,
        EV: 3,
        ASW: 22,
        LOS: 3,
        RNG: 4,
    },
    1575: {
        name: 'Abyssal Patrolling Attack Hawk Kai',
        nameJP: '深海攻撃哨戒鷹改',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        FP: 5,
        AERIAL_BOMB: 18,
        AA: 9,
        AR: 3,
        ACC: 9,
        EV: 4,
        ASW: 27,
        LOS: 3,
        RNG: 4,
    },
    1576: {
        name: 'Abyssal 12inch Triple Gun Mount',
        nameJP: '深海12inch三連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 16,
        AA: 3,
        AR: 2,
        ACC: 9,
        EV: 2,
        RNG: 3,
    },
    1577: {
        name: 'Abyssal 15inch Quadruple Gun Mount',
        nameJP: '深海15inch四連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 24,
        AA: 4,
        AR: 2,
        ACC: 8,
        EV: 1,
        RNG: 3,
    },
    1578: {
        name: 'Abyssal 15inch Late Model Twin Gun Mount',
        nameJP: '深海15inch連装砲後期型',
        icon: SpecialIcon.MainHighAngleGun,
        type: "MAIN_GUN_L",
        aaci_type: 'A_HAFD',
        FP: 19,
        AA: 8,
        AR: 1,
        ACC: 10,
        EV: 2,
        RNG: 3,
    },
    1579: {
        name: 'Abyssal 14inch Straight Twin Gun Mount',
        nameJP: '深海14inch海峡連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        icon: SpecialIcon.AbyssalLargeCaliberMainGun,
        FP: 17,
        AA: 4,
        AR: 3,
        ACC: 13,
        EV: 3,
        RNG: 3,
    },
    1580: {
        name: 'Abyssal Ambush Torpedo',
        nameJP: '深海待伏魚雷',
        type: "MIDGET_SUBMARINE",
        aaci_type: 'NONE',
        can_not_op_torpedo_midgetsub: true,
        TP: 19,
        ACC: 9,
        RNG: 1,
    },
    1581: {
        name: 'Abyssal Night Cat Fighter',
        nameJP: '夜猫深海艦戦',
        icon: SpecialIcon.NightFighters,
        type: "FIGHTER",
        aaci_type: 'NONE',
        b_type: 'B_NIGHTFIGHTER',
        FP: 2,
        AA: 11,
        ACC: 3,
        EV: 3,
        LOS: 2,
        RNG: 1,
    },
    1582: {
        name: 'Abyssal Night Dive Bomber',
        nameJP: '夜深海艦爆',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        b_type: 'B_NIGHTBOMBER2',
        AA_resist_ship: 0.6,
        AA_resist_fleet: 0.7,
        FP: 3,
        AERIAL_BOMB: 16,
        AA: 5,
        ACC: 4,
        ASW: 11,
        LOS: 6,
        RNG: 2,
    },
    1583: {
        name: 'Abyssal Night Revenge Torpedo Bomber',
        nameJP: '夜復讐深海艦攻',
        icon: SpecialIcon.NightTorpedoBombers,
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        b_type: 'B_NIGHTBOMBER',
        AA_resist_ship: 0.6,
        AA_resist_fleet: 0.7,
        FP: 4,
        AERIAL_TP: 15,
        AA: 6,
        ACC: 5,
        ASW: 12,
        LOS: 7,
        RNG: 2,
    },
    1584: {
        name: 'Abyssal 14inch Twin Gun Mount Kai',
        nameJP: '深海14inch連装砲改',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 22,
        AA: 4,
        AR: 4,
        ACC: 14,
        EV: 4,
        RNG: 3,
    },
    1585: {
        name: 'Abyssal 16inch Triple Gun Mount Kai',
        nameJP: '深海16inch三連装砲改',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 27,
        AA: 4,
        AR: 5,
        ACC: 20,
        RNG: 4,
    },
    1586: {
        name: 'Abyssal Patrolling Attack Hawk Kai Ni',
        nameJP: '深海攻撃哨戒鷹改二',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        FP: 9,
        AERIAL_BOMB: 27,
        AA: 10,
        AR: 3,
        ACC: 13,
        EV: 5,
        ASW: 29,
        LOS: 5,
        RNG: 4,
    },
    1587: {
        name: 'Abyssal 16inch Triple Gun Mount Kai Ni',
        nameJP: '深海16inch三連装砲改二',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 28,
        AA: 5,
        AR: 6,
        ACC: 24,
        EV: 3,
        RNG: 4,
    },
    1588: {
        name: 'Abyssal 5inch Twin Gun Mount Model C',
        nameJP: '深海5inch連装砲C型',
        type: "MAIN_GUN_S",
        aaci_type: 'A_GUN',
        FP: 6,
        AA: 3,
        ACC: 18,
        EV: 9,
        ASW: 6,
        RNG: 1,
    },
    1589: {
        name: 'Abyssal 5.5inch Twin Gun Mount Kai',
        nameJP: '深海5.5inch連装砲改',
        type: "MAIN_GUN_M",
        aaci_type: 'A_GUN',
        FP: 8,
        AA: 4,
        AR: 4,
        ACC: 19,
        EV: 7,
        ASW: 6,
        RNG: 2,
    },
    1590: {
        name: 'Abyssal Target',
        nameJP: '深海標的',
        type: "MIDGET_SUBMARINE",
        aaci_type: 'NONE',
        can_not_op_torpedo_midgetsub: true,
        FP: 4,
        TP: 18,
        ACC: 9,
        EV: 4,
        RNG: 4,
    },
    1591: {
        name: 'Abyssal 5inch Single Gun Mount Mk.30',
        nameJP: '深海5inch単装砲 Mk.30',
        type: "MAIN_GUN_S",
        aaci_type: 'A_HAGUN',
        icon: SpecialIcon.MainHighAngleGun,
        FP: 5,
        AA: 7,
        ACC: 20,
        EV: 8,
        ASW: 7,
        RNG: 2,
    },
    1592: {
        name: 'Abyssal 16inch Mk.VIII Twin Gun Mount Kai',
        nameJP: '深海16inch Mk.VIII連装砲改',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 23,
        AA: 4,
        AR: 3,
        ACC: 22,
        RNG: 3,
    },
    1593: {
        name: 'High-speed Abyssal Torpedo mod. 3',
        nameJP: '高速深海魚雷 mod.3',
        type: "TORPEDO",
        aaci_type: 'NONE',
        TP: 15,
        ACC: 10,
        EV: 3,
        RNG: 1,
    },
    1594: {
        name: 'Abyssal Sky Fortress (Reconnaissance Model)',
        nameJP: '深海空要塞(偵察型)',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        high_altitude_bomber: true,
        FP: 17,
        AERIAL_BOMB: 3,
        AA: 9,
        ACC: 3,
        LOS: 7,
        RNG: 4,
    },
    1595: {
        name: 'Abyssal Sky Fortress Ace (Reconnaissance Model)',
        nameJP: '深海空要塞Ace(偵察型)',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        high_altitude_bomber: true,
        FP: 17,
        AERIAL_BOMB: 7,
        AA: 17,
        ACC: 7,
        LOS: 9,
        RNG: 4,
    },
    1596: {
        name: 'Abyssal 6inch Triple New Rapid Fire Gun Mount',
        nameJP: '深海6inch三連装新型速射砲',
        type: "MAIN_GUN_M",
        aaci_type: 'A_GUN',
        FP: 14,
        AA: 13,
        ACC: 9,
        RNG: 2,
    },
    1597: {
        name: 'Abyssal Sky Fortress (Heavy Bomber Model)',
        nameJP: '深海空要塞(重爆型)',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        high_altitude_bomber: true,
        FP: 17,
        AERIAL_BOMB: 27,
        AA: 9,
        ACC: 3,
        LOS: 5,
        RNG: 4,
    },
    1598: {
        name: 'Abyssal Sky Fortress Ace (Heavy Bomber Model)',
        nameJP: '深海空要塞Ace(重爆型)',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        high_altitude_bomber: true,
        FP: 17,
        AERIAL_BOMB: 37,
        AA: 17,
        ACC: 7,
        LOS: 7,
        RNG: 4,
    },
    1599: {
        name: 'Abyssal 4.7inch Gun Mk.XII',
        nameJP: '深海4.7inch砲 Mk.XII',
        type: "MAIN_GUN_S",
        aaci_type: 'A_HAGUN',
        icon: SpecialIcon.MainHighAngleGun,
        FP: 6,
        AA: 6,
        ACC: 24,
        EV: 6,
        ASW: 12,
        RNG: 1,
    },
    1600: {
        name: 'Abyssal 8inch Twin Rapid Fire Gun Mount',
        nameJP: '深海8inch連装速射砲',
        type: "MAIN_GUN_M",
        aaci_type: 'A_GUN',
        FP: 10,
        AA: 2,
        ACC: 8,
        RNG: 2,
    },
    1601: {
        name: 'Abyssal 8inch Triple Gun Mount Mk.9',
        nameJP: '深海8inch三連装砲 Mk.9',
        type: "MAIN_GUN_M",
        aaci_type: 'A_GUN',
        FP: 12,
        AA: 2,
        ACC: 9,
        RNG: 2,
    },
    1602: {
        name: 'Abyssal 5inch Twin Dual-purpose Gun Mount (Concentrated Deployment)',
        nameJP: '深海5inch連装両用砲(集中配備)',
        type: "MAIN_GUN_S",
        aaci_type: 'A_HAFD',
        icon: SpecialIcon.MainHighAngleGun,
        FP: 7,
        AA: 18,
        ACC: 7,
        EV: 3,
        RNG: 2,
    },
    1603: {
        name: 'Abyssal Air Radar Mark.III + FCS',
        nameJP: '深海対空レーダーMark.III+FCS',
        type: "RADAR_L",
        aaci_type: 'A_AIRRADAR',
        AA: 19,
        ACC: 16,
        EV: 3,
        ASW: 11,
        LOS: 13,
    },
    1604: {
        name: 'Abyssal 5inch Twin Gun Mount Model A',
        nameJP: '深海5inch連装砲A型',
        type: "MAIN_GUN_S",
        aaci_type: 'A_GUN',
        FP: 6,
        TP: 6,
        AA: 2,
        ACC: 18,
        EV: 6,
        ASW: 4,
        RNG: 1,
    },
    1605: {
        name: 'Abyssal Submarine Electronic Armament',
        nameJP: '深海潜水艦搭載電子兵装',
        type: "SUBMARINE_RADAR",
        aaci_type: 'NONE',
        TP: 6,
        ACC: 22,
        EV: 6,
        LOS: 6,
        RNG: 1,
    },
    1606: {
        name: 'Abyssal 5inch Single High-angle Gun Mount Kai Ni',
        nameJP: '深海5inch単装高角砲改二',
        type: "MAIN_GUN_S",
        aaci_type: 'A_HAGUN',
        icon: SpecialIcon.MainHighAngleGun,
        FP: 1,
        AA: 5,
        ACC: 19,
        EV: 3,
        ASW: 2,
        RNG: 1,
    },
    1607: {
        name: 'Abyssal 5inch Twin High-angle Gun Mount Kai Ni',
        nameJP: '深海5inch連装高角砲改二',
        type: "MAIN_GUN_S",
        aaci_type: 'A_HAGUN',
        icon: SpecialIcon.MainHighAngleGun,
        FP: 2,
        AA: 6,
        ACC: 19,
        EV: 2,
        ASW: 2,
        RNG: 1,
    },
    1608: {
        name: 'Abyssal Night Operation Aviation Equipment',
        nameJP: '深海夜間航空作戦装備',
        type: "RADAR_L",
        aaci_type: 'NONE',
        FP: 3,
        ACC: 3,
        RNG: 4,
    },
    1609: {
        name: 'Abyssal 16inch Triple Gun Mount Mk.6',
        nameJP: '深海16inch三連装砲 Mk6',
        type: "MAIN_GUN_M",
        aaci_type: 'A_GUN',
        FP: 25,
        AA: 3,
        AR: 3,
        ACC: 25,
        EV: 4,
        RNG: 3,
    },
    1610: {
        name: 'Abyssal Seagull Reconnaissance Seaplane',
        nameJP: '深海カモメ水偵',
        type: "SEAPLANE",
        aaci_type: 'NONE',
        ACC: 4,
        EV: 3,
        ASW: 4,
        LOS: 6,
    },
    1611: {
        name: 'Abyssal Seamew Reconnaissance Seaplane',
        nameJP: '深海海猫水偵',
        type: "SEAPLANE",
        aaci_type: 'NONE',
        FP: 3,
        AA: 7,
        ACC: 6,
        EV: 4,
        ASW: 6,
        LOS: 7,
    },
    1612: {
        name: 'Abyssal 6inch Triple Main Gun Mount Mk.16',
        nameJP: '深海6inch三連装主砲 Mk.16',
        type: "MAIN_GUN_M",
        aaci_type: 'A_GUN',
        FP: 13,
        AA: 6,
        ACC: 9,
        ASW: 3,
        RNG: 2,
    },
    1613: {
        name: 'Mediterranean 12inch/46 Twin Gun Mount',
        nameJP: '地中海12inch/46 連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 14,
        AR: 3,
        ACC: 8,
        EV: 4,
        RNG: 3,
    },
    1614: {
        name: 'Mediterranean 12inch/46 Triple Gun Mount',
        nameJP: '地中海12inch/46 三連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 17,
        AR: 3,
        ACC: 9,
        EV: 3,
        RNG: 3,
    },
    1615: {
        name: 'Mediterranean 12.6inch/44 Twin Gun Mount',
        nameJP: '地中海12.6inch/44 連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 16,
        TP: 7,
        AR: 3,
        ACC: 10,
        EV: 5,
        RNG: 3,
    },
    1616: {
        name: 'Mediterranean 12.6inch/44 Triple Gun Mount',
        nameJP: '地中海12.6inch/44 三連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 19,
        TP: 7,
        AR: 3,
        ACC: 11,
        EV: 4,
        RNG: 3,
    },
    1617: {
        name: 'Abyssal Night Cat Fighter II',
        nameJP: '夜猫深海艦戦II',
        type: "FIGHTER",
        aaci_type: 'NONE',
        icon: SpecialIcon.NightFighters,
        b_type: 'B_NIGHTFIGHTER',
        FP: 3,
        AA: 13,
        ACC: 4,
        EV: 3,
        LOS: 2,
        RNG: 1,
    },
    1618: {
        name: 'Abyssal Night Dive Bomber II',
        nameJP: '夜深海艦爆II',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        b_type: 'B_NIGHTBOMBER2',
        FP: 4,
        AERIAL_BOMB: 17,
        AA: 6,
        ACC: 5,
        ASW: 12,
        LOS: 6,
        RNG: 2,
    },
    1619: {
        name: 'Abyssal Night Revenge Torpedo Bomber II',
        nameJP: '夜復讐深海艦攻II',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        icon: SpecialIcon.NightTorpedoBombers,
        b_type: 'B_NIGHTBOMBER',
        FP: 5,
        AERIAL_TP: 17,
        AA: 7,
        ACC: 6,
        ASW: 13,
        LOS: 7,
        RNG: 2,
    },
    1620: {
        name: 'Abyssal Two-seat Fighter-bomber Hawk',
        nameJP: '深海戦爆複座鷹',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        AA_resist_ship: 0.6,
        AA_resist_fleet: 0.7,
        FP: 5,
        AERIAL_BOMB: 12,
        AA: 10,
        AR: 3,
        ACC: 10,
        EV: 4,
        ASW: 20,
        LOS: 3,
        RNG: 4,
    },
    1621: {
        name: 'Abyssal Two-seat Fighter-bomber Hawk Kai',
        nameJP: '深海戦爆複座鷹改',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        AA_resist_ship: 0.6,
        AA_resist_fleet: 0.7,
        FP: 6,
        AERIAL_BOMB: 16,
        AA: 11,
        AR: 3,
        ACC: 12,
        EV: 5,
        ASW: 24,
        LOS: 3,
        RNG: 4,
    },
    1622: {
        name: 'Abyssal Quadruple (Oxygen) Torpedo Mount Late Model',
        nameJP: '深海四連装(酸素)魚雷後期型',
        type: "MIDGET_SUBMARINE",
        aaci_type: 'NONE',
        can_not_op_torpedo_midgetsub: true,
        TP: 14,
        ACC: 8,
        EV: 2,
        RNG: 1,
    },
    1623: {
        name: 'Abyssal 5inch Twin Gun Mount Model D',
        nameJP: '深海5inch連装砲D型',
        type: "MAIN_GUN_S",
        aaci_type: 'A_GUN',
        FP: 7,
        AA: 4,
        AR: 1,
        ACC: 19,
        EV: 8,
        ASW: 6,
        RNG: 1,
    },
    1624: {
        name: 'Abyssal Quintuple (Oxygen) Torpedo Mount Late Model',
        nameJP: '深海五連装(酸素)魚雷後期型',
        type: "MIDGET_SUBMARINE",
        aaci_type: 'NONE',
        can_not_op_torpedo_midgetsub: true,
        TP: 18,
        ACC: 9,
        EV: 2,
        RNG: 1,
    },
    1625: {
        name: 'Abyssal Twin-engine Land-based Dive Bomber',
        nameJP: '深海双発陸爆',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        is_skip_bomber: true,
        AERIAL_BOMB: 12,
        AERIAL_TP: 6,
        AA: 3,
        ACC: 2,
        ASW: 5,
        LOS: 3,
    },
    1626: {
        name: 'Abyssal Twin-engine Land-based Dive Bomber Ace',
        nameJP: '深海双発陸爆Ace',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        is_skip_bomber: true,
        AERIAL_BOMB: 17,
        AERIAL_TP: 7,
        AA: 5,
        ACC: 3,
        ASW: 7,
        LOS: 4,
    },
    1627: {
        name: 'Abyssal 5inch Twin Gun Mount Model C',
        nameJP: '深海5inch連装砲C型',
        type: "MAIN_GUN_S",
        aaci_type: 'A_GUN',
        FP: 6,
        AA: 2,
        AR: 2,
        ACC: 18,
        EV: 9,
        ASW: 5,
        RNG: 1,
    },
    1630: {
        name: 'Abyssal Sky Super Fortress',
        nameJP: '深海空超要塞',
        type: "LAND_BASED_BOMBER",
        aaci_type: 'NONE',
        FP: 18,
        AERIAL_BOMB: 33,
        AA: 12,
        ACC: 5,
        LOS: 4,
        RNG: 5,
    },
    1631: {
        name: 'Abyssal Sky Super Fortress Kai',
        nameJP: '深海空超要塞改',
        type: "LAND_BASED_BOMBER",
        aaci_type: 'NONE',
        FP: 18,
        AERIAL_BOMB: 44,
        AA: 19,
        ACC: 9,
        LOS: 6,
        RNG: 5,
    },
    1632: {
        name: 'Abyssal Aviation Maintenance Bugs',
        nameJP: '深海航空整備蟲',
        type: "SCAMP",
        aaci_type: 'NONE',
        FP: 16,
        AERIAL_BOMB: 12,
        TP: 12,
        AA: 8,
        ACC: 8,
        ASW: 32,
        RNG: 5,
    },
    1633: {
        name: 'Abyssal Aviation Maintenance Bugs Pro',
        nameJP: '深海航空整備蟲pro',
        type: "SCAMP",
        aaci_type: 'NONE',
        FP: 24,
        AERIAL_BOMB: 16,
        TP: 16,
        AA: 8,
        ACC: 16,
        ASW: 48,
        RNG: 5,
    },
    1634: {
        name: 'Abyssal Rigging Assault General Seaplane',
        nameJP: '深海艤装水上汎用襲撃機',
        type: "SEAPLANE_BOMBER",
        aaci_type: 'NONE',
        is_skip_bomber: true,
        FP: 7,
        AERIAL_BOMB: 17,
        TP: 14,
        AA: 7,
        ACC: 9,
        EV: 6,
        RNG: 5,
    },
    1635: {
        name: 'Abyssal Assault Torpedo Bomber',
        nameJP: '深海突破襲撃機',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        is_skip_bomber: true,
        FP: 6,
        AERIAL_BOMB: 11,
        AERIAL_TP: 11,
        AA: 4,
        ACC: 4,
        RNG: 5,
    },
    1636: {
        name: 'Abyssal Assault Torpedo Bomber Ace',
        nameJP: '深海突破襲撃機Ace',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        is_skip_bomber: true,
        FP: 9,
        AERIAL_BOMB: 16,
        AERIAL_TP: 13,
        AA: 6,
        ACC: 6,
        RNG: 5,
    },
    1637: {
        name: 'Coastal Ambush Semi-Submersible Torpedo Boat',
        nameJP: '沿岸突撃半水中魚雷艇',
        type: "MIDGET_SUBMARINE",
        aaci_type: 'NONE',
        TP: 18,
        ACC: 9,
        RNG: 1,
    },
    1638: {
        name: 'Abyssal 3inch Single High-angle Gun Mount + Deck Machine Gun',
        nameJP: '深海3inch単装高角砲+甲板機銃',
        type: "MAIN_GUN_S",
        aaci_type: 'A_GUN',
        FP: 5,
        AA: 7,
        ACC: 3,
        RNG: 1,
    },
    1639: {
        name: 'Abyssal Active Sonar & Abyssal Calibrated Radar',
        nameJP: '深海水中探信儀 & 深海調整電探',
        type: "RADAR_S",
        aaci_type: 'A_AIRRADAR',
        icon: SpecialIcon.AbyssalSmallSonar,
        AA: 3,
        ACC: 13,
        EV: 8,
        ASW: 16,
        LOS: 5,
        RNG: 2,
    },
    1640: {
        name: 'Abyssal Observation Barrage Balloon',
        nameJP: '深海観測阻塞気球',
        type: "BARRAGE_BALLOON",
        aaci_type: 'NONE',
        icon: SpecialIcon.BarrageBalloons,
        FP: 1,
        AR: 1,
        ACC: 3,
        EV: 3,
    },
    1641: {
        name: 'Abyssal Standard 14inch/45 Twin Gun Mount',
        nameJP: '深海標準14inch/45 連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 16,
        AR: 3,
        ACC: 4,
        EV: 2,
        RNG: 3,
    },
    1642: {
        name: 'Abyssal Standard 14inch/45 Triple Gun Mount',
        nameJP: '深海標準14inch/45 三連装砲',
        type: "MAIN_GUN_L",
        aaci_type: 'A_GUN',
        FP: 19,
        AR: 4,
        ACC: 6,
        EV: 1,
        RNG: 3,
    },
    1643: {
        name: 'Abyssal 3.7cm FlaK',
        nameJP: '深海3.7cm FlaK',
        type: "AA_GUN",
        aaci_type: 'A_AAGUN',
        FP: 1,
        AA: 8,
        ACC: 4,
        EV: 1,
    },
    1644: {
        name: 'Abyssal 5inch Single Gun Mount Mk.30 + GFCS',
        nameJP: '深海5inch単装砲 Mk.30+GFCS',
        type: "MAIN_GUN_S",
        aaci_type: 'A_HAFD',
        icon: SpecialIcon.MainHighAngleGun,
        FP: 6,
        AA: 12,
        ACC: 22,
        EV: 9,
        ASW: 9,
        RNG: 2,
    },
    1645: {
        name: 'Abyssal 533mm Quintuple Torpedo Mount + Abyssal SG',
        nameJP: '深海533mm 5連装魚雷+深海SG',
        type: "TORPEDO",
        aaci_type: 'NONE',
        TP: 18,
        ACC: 12,
        EV: 4,
        ASW: 4,
        LOS: 12,
        RNG: 2,
    },
    1646: {
        name: 'Abyssal Hedgehog Mk.10',
        nameJP: '深海Hedgehog Mk.10',
        type: "DEPTH_CHARGE",
        aaci_type: 'NONE',
        ACC: 4,
        EV: 2,
        ASW: 22,
    },
    1647: {
        name: 'GFCS + Abyssal 5inch Twin Gun Mount Mk.32',
        nameJP: 'GFCS+深海5inch連装砲 Mk.32',
        type: "MAIN_GUN_M",
        aaci_type: 'A_HAFD',
        icon: SpecialIcon.MainHighAngleGun,
        FP: 11,
        AA: 19,
        ACC: 23,
        EV: 7,
        ASW: 11,
        RNG: 2,
    },
    1648: {
        name: 'Abyssal Combat Autogyro Seagull',
        nameJP: '深海対戦回転翼海鴎',
        type: "AUTOGYRO",
        aaci_type: 'NONE',
        FP: 8,
        AERIAL_BOMB: 18,
        ACC: 18,
        ASW: 18,
        LOS: 4,
        RNG: 3,
    },
    1649: {
        name: '15.2cm Abyssal Triple Gun Mount',
        nameJP: '15.2cm深海三連装砲',
        type: "MAIN_GUN_M",
        aaci_type: 'A_GUN',
        FP: 9,
        AA: 3,
        ACC: 3,
        ASW: 3,
        RNG: 2,
    },
    1650: {
        name: 'Abyssal Buffalo Fighter Mk.II',
        nameJP: '深海野牛艦戦 Mk.II',
        type: "FIGHTER",
        aaci_type: 'NONE',
        icon: SpecialIcon.NightFighters,
        b_type: 'B_NIGHTFIGHTER',
        FP: 1,
        AA: 11,
        ACC: 3,
        EV: 3,
        LOS: 2,
        RNG: 1,
    },
    1651: {
        name: 'Abyssal Dauntless Dive Bomber Mk.II',
        nameJP: '深海不屈艦爆 Mk.II',
        type: "DIVE_BOMBER",
        aaci_type: 'NONE',
        b_type: 'B_NIGHTBOMBER2',
        FP: 2,
        AERIAL_BOMB: 13,
        AA: 6,
        ACC: 8,
        EV: 3,
        ASW: 11,
        LOS: 7,
        RNG: 2,
    },
    1652: {
        name: 'Abyssal Devastation Torpedo Bomber Mk.II',
        nameJP: '深海打撃艦攻 Mk.II',
        type: "TORPEDO_BOMBER",
        aaci_type: 'NONE',
        icon: SpecialIcon.NightTorpedoBombers,
        b_type: 'B_NIGHTBOMBER',
        FP: 3,
        AERIAL_TP: 11,
        AA: 3,
        ACC: 6,
        ASW: 12,
        LOS: 4,
        RNG: 2,
    },
};